### ISSUE TITLE
Set up Github Actions runners on NCI for deployment workflows

### ISSUE THREAD

**Issue by echus** [ACCESS-NRI/build-ci#5]
See https://github.com/ACCESS-NRI/nci_runner/issues/1

**Comment by CodeGat** [comment]
Update:
Using the runner on https://github.com/ACCESS-NRI/github-runner, with CI from https://github.com/ACCESS-NRI/test
We are running into $PATH issues it seems - the github runner attempts to self update, but can't because `tar` doesn't work:
```
Oct 03 04:08:59 nirin-github-runner.novalocal run.sh[7898]: Runner update in progress, do not shutdown runner.
Oct 03 04:08:59 nirin-github-runner.novalocal run.sh[7898]: Downloading 2.309.0 runner
Oct 03 04:09:02 nirin-github-runner.novalocal run.sh[7898]: Runner update process finished.
Oct 03 04:09:03 nirin-github-runner.novalocal run.sh[7898]: An error occurred: tar -xzf
```
This propagates to the other jobs, as well. When we attempt to do a simple `echo` as a CI job, it notes that `sh: command not found` on one run, and `tar: command not found` on another. 

Seems to be something to do with the runners use of $PATH, maybe? Tagging @echus for when she has availibility. Will attempt to rebuild NixOS and start again. 

References https://github.com/ACCESS-NRI/github-runner/issues/1

**Comment by CodeGat** [comment]
Update for today:
I've solved the PATH issue by passing `Environment="PATH=<PATH from doing 'su runner && echo $PATH on the VM>`. We can access `tar` and the the other programs on the PATH. However, it is complaining that there is no `.../.github-runner/safe_sleep.sh` file:
```
Oct 04 03:46:46 nirin-github-runner.novalocal run.sh[36926]: Runner update in progress, do not shutdown runner.
Oct 04 03:46:47 nirin-github-runner.novalocal run.sh[36926]: Downloading 2.309.0 runner
Oct 04 03:47:11 nirin-github-runner.novalocal run.sh[36926]: Waiting for current job finish running.
Oct 04 03:47:12 nirin-github-runner.novalocal run.sh[36926]: Generate and execute update script.
Oct 04 03:47:12 nirin-github-runner.novalocal run.sh[36926]: Runner will exit shortly for update, should be back online within 10 seconds.
Oct 04 03:47:12 nirin-github-runner.novalocal run.sh[36983]: /home/runner/.github-runner/_work/_update.sh: /home/runner/.github-runner/safe_sleep.sh: /bin/bash: bad interpreter: No such file or directory
... does that 100000 times before completing
```

**Comment by aidanheerdegen** [comment]
Do we switch to using an OS that is a closer match to GitHub runners? 

I seem to recall that running the runner inside a container (which would be quite nice and might help to create a compatible environment) doesn't work, but I can't recall why. @echus would know the details.

**Comment by CodeGat** [comment]
I don't want to give up on using NixOS until I've went through solutions with Varvara, it does have a lot of pluses and maybe it's just my inexperience with the operating system.

**Comment by echus** [comment]
Thanks for the detailed investigation @CodeGat. We should be able to specify all of those additional dependencies we need to get installed in configuration.nix:

```
packages = with pkgs; [
  github-runner
  <extra packages here>
];
```

Have a look at https://search.nixos.org/packages.

@aidanheerdegen yeah, unfortunately the Github runner container currently doesn't support running actions inside containers - https://github.com/actions/runner/issues/406

If that issue gets addressed in the future that would definitely be the way to go.

The reason for choosing NixOS is it allows us to define an entire system configuration programmatically. This allows us to bring runner VMs up and down quickly and reproducibly in a similar way to containers. The alternative would be using something like Ansible to automate setting up each VM, however this is time consuming and not always reproducible. IMO if we can get this working on NixOS it would be the ideal solution in the absence of being able to use containers.

**Comment by CodeGat** [comment]
Update for today:
The runner works - I have installed and configured `git` and `docker`, although haven't got to testing the actual dependency-image-building workflow as there will need to be some security hardening going on in `build-ci` before we add the self-hosted runner to the public repo. 

**Strange Things**
For some reason, when it is attempting to auto-update, the version of `github-runner` installed can't find the `safe_sleep.sh` file (it is running the `run-helper.sh` in the `/nix/store/...github-runner.../` directory) so the update fails. Running `find -name 'safe_sleep.sh -type f` gives me:
```
./home/runner/.github-runner/safe_sleep.sh
./home/runner/.github-runner/_work/_update/safe_sleep.sh
```
so it seems to exist somewhere, at least. 

The python issue still remains - being unable to install versions of python because none of them are in here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json - not sure where to go for this one.

**Comment by CodeGat** [comment]
As an update, the reason why we can't setup python on the runner is because nixOS isn't supported any of the versions of (Github Actions) Python. Only `win32`, `darwin` and `linux` platforms are supported, where `linux` platform versions are `20.04` and `22.04`.

**Comment by CodeGat** [comment]
An update for today:
* I attempted to set up a rocky linux runner but couldn't ssh in as root to install git/docker
* Attempted to remove the python dependency regarding `jsonschema` - existing third party actions are unmaintained and broken, so the only other option is to install `ajv-cli` via `npm`.

**Comment by CodeGat** [comment]
Update for today:
* We have success with the Ubuntu GitHub Runner! (See test run here: https://github.com/ACCESS-NRI/test/actions/runs/6501920462) 
* We also have success with multiple runners on the one VM (see https://github.com/ACCESS-NRI/test/actions/runs/6502180136)
* Now we just need to give them proper PATs and make them org runners instead of repo runners!
* Nirin runner has been taken offline :'(

**Comment by CodeGat** [comment]
Update for today (part 2!!!)
* We now have 4 org-scoped ubuntu runners on the same (now beefed up) machine using the existing PAT that will expire November 1st. When it expires, we will have to reconfigure the runners to all have a new PAT. To do this, we run:
```
sudo ./svc.sh stop  # stop the runner
sudo ./svc.sh uninstall  # uninstall the systemd service
./config.sh remove --token <TOKEN_FROM_REMOVE_RUNNER_WEB_GUI>  # remove the config so we can regenerate it with a new token

./config.sh --url https://https://github.com/ACCESS-NRI --pat <ORG_PAT>  # configure the org runner again with the new PAT
sudo ./svc.sh install  # create the systemd service
sudo ./svc.sh start  # start the runner!
```

**Comment by aidanheerdegen** [comment]
Do we have an answer yet as to whether the runners can do dynamic scaling?

These docs seem to suggest yes, but the solutions they mention require either Kubernetes or AWS:

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners

**Comment by CodeGat** [comment]
Yes we can have autoscaled runners, but we would need to have them as ephemeral runners hosted on Kubernetes or AWS, which could be a bit of setup, and I'm not sure how it works on Nirin. Could it be classed as an iterative improvement, or is this required?
What are your thoughts, @Quartzer2 ?

**Comment by Quartzer2** [comment]
Still have to familiarise myself a bit, but I think it would be more a matter of utilising kubernetes on nirin (if we can) or hosting on AWS (which I'm not all that familiar with - been using google cloud more).

I think the former would be preferable. I have some experience with kubernetes. More so with docker swarm, though that integrates fairly seamlessly with k8s.

**Comment by aidanheerdegen** [comment]
I'd definitely class it as an iterative improvement. If involved a bunch more work and infrastructure then I'd probably say not worth it for the time being.

To clarify, is the only way we we can have more runners to instantiate more runners, each of which needs to be administered separately? I'm wondering if we wanted, say, 20 runners, would we have to go and tell each one to get cracking, and also manually reconfigure each one when PATs expired etc?

**Comment by CodeGat** [comment]
> To clarify, is the only way we we can have more runners to instantiate more runners, each of which needs to be administered separately? I'm wondering if we wanted, say, 20 runners, would we have to go and tell each one to get cracking, and also manually reconfigure each one when PATs expired etc?

Correct. They are all separate. The reconfiguration (with just a single PAT that is used by all runners) can be mitigated somewhat by having a long-lived PAT (but not too long! maybe 6mo)

**Comment by CodeGat** [comment]
Closing this issue as the original goal was met (setting up runners for deployment workflows). The issues above are future steps in this direction, as discussed.
