### ISSUE TITLE
Allow to build a package with a specific version/commit of ACCESS-NRI/spack_packages

### ISSUE THREAD

**Issue by micaeljtoliveira** [ACCESS-NRI/build-ci#6]
For reproducibility, it might be necessary to build a package using an older version of ACCESS-NRI/spack_packages.

**Comment by aidanheerdegen** [comment]
Agreed. We should have the capability to specify which version should be used, and that version should be encoded in the container name or metadata in some way.

**Comment by CodeGat** [comment]
In terms of encoding the spack_packages version into the base-spack image, does anyone have any opinions on how this should be done? 
If we tag the image of base-spack with the version of the spack_packages repo that we specify, there could be a bunch of `base-spack:main` packages generated, as the default spack_packages repo version will be the main branch. This would lead to quite nice package names (like `base-spack:<spack_packages hash/branch/tag>`.
Alternatively, it could be inbuilt into the container name, so we would have `base-spack-main:latest`, (or `base-spack-<spack_packages commit hash/branch/tag>:latest). This would mean that we could have multiple versions of a base-spack image using a certain version of spack_packages.

**Comment by echus** [comment]
@CodeGat sorry I overlooked something in that pull request. We'll also need to modify `build-and-push-image-build.yml` to use the specified spack_packages version. This probably means we'll need to add a tag specifying the spack_packages version used in each image build, which will have downstream effects in all of the packages we're building images for. Will need to modify their workflow files to specify the spack_packages version we're using there as well.

I think the behaviour we want in the model packages is using the spack_packages main branch by default, and an optional input to use a different version if specified. Perhaps using manual inputs so it can just be input via the web interface - https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/

**Comment by aidanheerdegen** [comment]
> I think the behaviour we want in the model package workflows is using the spack_packages:main image by default, and an optional input to use a different version if specified.

This would mean the model package workflows would, by default, test against the latest `main` version of spack_packages.

I can see the value in that the CI would pick up if there were errors introduced in spack_packages, but I also think the model CI needs to test a known, tagged, version of spack_packages as it's stable configuration. That tag can be updated to point to new er versions of spack_packages as it is updated and confirmed good/reproducible.

I *think* we will also need to run model build CI against specific versions of spack_packages which represent released versions we support. I believe this is the case because we need to have reproducible builds with unchanging spack hashes for build and model provenance, and I think changing spack_packages could affect the concretized build hashes. But very happy to be corrected.

**Comment by CodeGat** [comment]
So, in that case, should it be required that you give a tagged version of spack_packages, and not default to branch `main`? Just making sure I understand correctly

**Comment by aidanheerdegen** [comment]
> So, in that case, should it be required that you give a tagged version of spack_packages, and not default to branch `main`? Just making sure I understand correctly

Not required, there is value in being able to test against the default `main`, but we definitely would need to be able test against specific versions of `spack_packages` for certain use cases.
