### ISSUE TITLE
Investigate the feasibility of pre-commit hooks over CI checks for formatting

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#71]
**Description**
During the last CI planning meeting, @echus mentioned the possibility of using pre-commit hooks for enforcing formatting of various languages, among other things. Investigate the pros and cons of this method compared to:
* Utilizing GitHub Actions existing `black` formatter/linter as an action `on.pull_request.sync` as a check that must pass before merge. Don't autoformat existing code. 
* Utilizing GitHub Actions existing `black` formatter/linter as an automatic formatter `on.pull_request.merge_group`. 

**Questions**
* Do we need to get devs to install/do anything for these pre-commit hooks to work?
* Is this a conversation that needs to be had with the wider dev team regarding formatting etc?

**Comment by CodeGat** [comment]
As an update - maybe we want these checks to be part of CI, but not hold up merges.

**Comment by CodeGat** [comment]
*Pre-Commit Hooks*
One of the issues with pre-commit hooks over CI checks for code styling and consistency is that we would need the entire development team to adopt it, as well as any new people. It is a simple addition to their work environment, but not having it would mean that non-standardized code would get in, and be relatively hard to track. Furthermore, in future, if we need to add any new checking software or error classes etc the onus is on the developer to adopt them, rather than on the CI maintainer/repository. 

*CI Checks*
Having the CI checks be part of the PR process gives tractable feedback on PRs and commits in the web UI that pass or fail these styling checks. 
Additions to the checks are easy, visible and centralised in a repository rather than getting multiple people to add pre-commit config.
Checks can also be designated as required or not.

Adding @echus and @aidanheerdegen for any further discussion.

**Comment by echus** [comment]
Agree that CI checks for code formatting should definitely be run in any case so that non-standardised code can't enter the codebase. I would however be cautious about running code reformatters like black as part of the CI process, rather than formatting checks only, for a couple of reasons:

1. This may create an issue where reformatting breaks the PR, which could be a confusing situation for developers and is clunky to fix if reformatting is only done remotely after a commit is done.
2. Often you'll need to go back and forth with the formatter if it requires manual intervention e.g. for overlength comments or non-standard lines of code (which in my experience is often). This would be pretty clunky and frustrating if relying only on CI to do it rather than being able to fix up any errors locally before pushing.

My suggestion would be combining both CI code formatting checks and adding standard pre-commit configs to each repository to do code formatting and linting locally. We can include a setup script for ease of use to install and enable pre-commit in a single step. Developers then can reformat their code and test it locally before committing, while the CI checks serve to enforce code formatting rules without modifying the codebase.

**Comment by CodeGat** [comment]
Ah yes @echus, forgot to mention that we wouldn't be doing any reformatting as part of the CI, just checks that it is standardised

**Comment by CodeGat** [comment]
For pre-commit configs, would that be something like https://pre-commit.com/ in which you add a `.pre-commit-config.yaml` to a repo which notes what to check?

**Comment by echus** [comment]
@CodeGat yep exactly. An example one from one of my Python projects if it helps:

```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: 'migrations'
    -   id: trailing-whitespace
        exclude: 'migrations'
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3
        exclude: 'migrations'
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8

```

**Comment by CodeGat** [comment]
Closing the issue (but can be reopened if there is more to say) with the following findings:
* CI formatting checks give visibility and tractability to a codebases compliance with standards. However, it shouldn't modify the codebase automatically, as especially aggressive autoformatters can introduce new bugs or become a back-and-forth conversation with the formatter over PR.
* Pre-commit hooks can offer this sort of modification to the codebase locally rather than remotely. They can be configured on a per-repository basis, using a config file located in the repository, for easy install. 
* Rather than using one over the other, they can complement each other, with pre-commit modifying, and CI checks verifying.
